sudo: required

language: node_js
node_js: '10'

cache: yarn

services:
  - docker

env:
  global:
    - CODECLIMATE_REPO_TOKEN=06f5b199c1d9bb6f814adf03807ad1df9b6184d4a268daba4672f4f95418ac7e

notifications:
  email: false
  slack:
    secure: qi+24/+aauzw4pgeIEGrQkeDBB4lhM77eORc7YEhwMwhZ229xEtTF+4dYXk1R96uIEv+bMROqgq8Xitf/3zvF4auT9hJ+1e8FlExqB0s7dngxIXLRzSsaNEN3jaBefyl9mQ5/pax6C1p9QHDvIkP3l5XwfpLPJb7bKLHGOz1iMy3ajP8l+PQGdPWfzr+yql5m1Jb5LlQM/NRMsP69b385uKCv1jsmxNrhtd6QdXJuH7iwJRO8PWIj3rz8aPqGCedgGC7NbmmDUKlrbUi1T70MOC6VYWEw3Vv4ehdeqqDUPH2+B10AVu9AuSFI547WkRyutjyaMgWgBCweHSBVzVPbpVqkRVRS3p/KDEjvSrlTJLA3ALXT79ibBvL3VTyOlTRS4Wlrgke31wWqFoO+mGymn3mqP59nY7bJJdqEKv8SMKxB8f6Kpdp1xTGvVlocRpNytQ+ejG7SvCjZMHJTYAsl8FXDuw4BLhvnkpo1ZVUJcd37mqpcvq1scGddVsdDCnOb3X2Y9bAJXC5Hjxm+OdJ0UEvcmMOaSCSG0+WX/5BNhu84VusljTCbTuLBNQJHav7V8u0/4RRHPFvEWEGjqvbJ2CY49pd6EYQ9toj8d+zpOF7jHoZsW3rFm/7Kc4gyzeCJAovpirVccnZbGMsxvDmCfVOqcVj0FPvWY6pUzsiDL4=

script: yarn run test:all
after_script:
  - yarn run test:reporter

deploy:
  provider: releases
  api_key:
    secure: T9OeyzMIoCkqBSB7nzmuiFbEwrw9W6myTTDZdowTy3W+T3wCcpHoqKzB5GfCH8YY+FS1D/Q5W8SJ0lbdTf9GTnIhidYTM2f/x5SHFTOzALEX3IXWORXSpo8QlflHLXQpqT1oIyYkIf9ONHclpXHai4l7FT1IMcaF9ibx4StqtHgEp6Ewx5o+CkIOsLk60a3auo2JMFIjNufSIXKZscxRrYKxfeEDEVDsjhZac7jVwps/sDVrOOhtrgAH4UWrrX3S6ODhkgGHH7Ck8k+6DGqVK4c62JyfSUgHEnGvQWQr635J/dI8jeDD5eVoyjy7EHbs4Qeefln8EJ3X9e6V/hHLDDil3euRUnLMYAgauvj1ql+hh9+Sl4vRIu6wOCkH0yq+L4d3KNTJRY9hFGRowoeSINnM8dIOIzRsykdILYyUXG4FQbgaO1QeuGkuvWAeDFmxmEnNbDXoCu+2hzItuFqIFUpcP7jmx0l2yvuNge7qnknGSTPK+Rk5VhJsHP0c2oUAe2KQsFZFSmhx69E1ibyFGt0j8eOMKv8Xj7ewxAJGYam5TZAJccfA56TjV879cPdUcNms3nAzrRLwQXoUo015WtDN4BcL8XgewLSA889o3zNWYN/wZzKqXadSFN7YuFVWSbGM5TTZXrr8gDHr1IkKvAyApSQskpE9mHeRAap2KAs=
  on:
    branch: /^release-.*$/

after_deploy:
  - 'curl -H ''Content-Type: application/json'' --data ''{"build": true}'' -X POST $DOCKER_HUB_URL;'
