sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js: '8'
notifications:
  email: false
  slack:
    secure: Mxaom+mwnpohiP1oFI51ciBZD4eTdL6+6ORYuq9QmXH/SBfhqRYqukrS8ykC+KkgLE9m3IRh1lPNdTA0i0ArKaVzDxNRjByXG3PmFvrLC9BTrRseqkMFqGHhJp4V9X1AbhkEG9CtmuSm1Q64EiNxs+YV/ROWWo7r6TUp89grfx0nou47cb6Q80/p+zTXoLQDbFutrZRKXg7VNtE5XNuY8zUQPsDBruni0ixSO4ypDL6vunaGHilGfwvs61ZYBCJ8NaANXkagHgFlrZyIjYn2cGzcJ6PRfBrB7knWCmaIGbJaSBXp4D4zhs65zy1WUAMAMkYlx6CfG0eI6U5j2OmiiTMDlnOKyTgfNmX6ighdfDE3G9r2DwzhBYGIEozrNVDlSNR7sh+gRomY4R36kTGkxKE5W450QGWgHiQDoypafs98eGZ6QhGsp0GCkaFsdvlWPhTv854A1EXlOKXNLNu5kUaTD8Cf/TtjAvWTVLB40yXm5iSJcCFKKIduZ/4u7Z/fPCGNv7TexVueQUBUeZF468bux+3JKIgjFzIpAbPL458jX4KiumMn+qAPKrDYztqkLUTWrgC3pTw30htXhEKyZJKWh2YBnBtHBs3svuA3xMRtfGIQ1R7XAAev7Z63En/ePZQuZfopalVvEpIpv8v0xPXuJDqY9aBTmtyOR3UoKYg=

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16
  - yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
    curl -H "Content-Type: application/json" --data '{"build": true}' -X POST $DOCKER_HUB_URL;
    fi